// src/react/components/route-view.tsx
import { observer } from 'mobx-react-lite';
import type {
  AnyAbstractRouteEntity,
  AnyRoute,
  AnyVirtualRoute,
} from 'mobx-route';

export type RouteViewComponent<TRoute extends AnyAbstractRouteEntity> =
  React.ComponentType<RouteViewProps<TRoute>>;

interface RouteViewConfigWithoutRoute {
  children?: React.ReactNode | (() => React.ReactNode);
}

export interface RouteViewConfigWithRoute<
  TRoute extends AnyAbstractRouteEntity,
> {
  route: TRoute;
  view?: RouteViewComponent<TRoute>;
  /**
   * Case when route is not opened
   */
  fallback?: React.ReactNode;
  children?:
    | React.ReactNode
    | ((
        params: RouteViewProps<TRoute>['params'],
        route: TRoute,
      ) => React.ReactNode);
}

export type RouteViewConfig<TRoute extends AnyAbstractRouteEntity> =
  | RouteViewConfigWithRoute<TRoute>
  | RouteViewConfigWithoutRoute;

export type RouteViewProps<TRoute extends AnyAbstractRouteEntity> = {
  children?: React.ReactNode;
  params: TRoute extends AnyRoute
    ? Exclude<TRoute['params'], null | undefined>
    : TRoute extends AnyVirtualRoute
      ? TRoute['params']
      : never;
};

type RouteViewBaseComponent = <TRoute extends AnyAbstractRouteEntity>(
  props: RouteViewConfig<TRoute>,
) => React.ReactNode;

function RouteViewBase<TRoute extends AnyAbstractRouteEntity>(
  props: Readonly<RouteViewConfig<TRoute>>,
): React.ReactNode {
  let Component: React.ComponentType<any> | undefined;

  if (!('route' in props)) {
    return typeof props.children === 'function'
      ? props.children()
      : props.children;
  }

  const isOpening =
    'isOpening' in props.route &&
    Boolean((props.route as { isOpening?: boolean }).isOpening);

  if (!props.route.isOpened && !isOpening) {
    return props.fallback ?? null;
  }

  Component = props.view;

  const params: any = 'params' in props.route ? props.route.params : {};

  if (Component) {
    return <Component params={params}>{props.children}</Component>;
  }

  if (typeof props.children === 'function') {
    return props.children(params, props.route);
  }

  return props.children;
}

export const RouteView = observer(RouteViewBase) as RouteViewBaseComponent;

// packages/solid/src/components/route-view.tsx
import type {
  AnyAbstractRouteEntity,
  AnyRoute,
  AnyVirtualRoute,
} from 'mobx-route';
import type { Component, JSX } from 'solid-js';
import { Dynamic } from 'solid-js/web';
import { useRouteViewGroup } from './route-view-group-context.js';

export type RouteViewComponent<TRoute extends AnyAbstractRouteEntity> =
  Component<RouteViewProps<TRoute>>;

interface RouteViewConfigWithoutRoute {
  children?: JSX.Element | (() => JSX.Element);
}

export interface RouteViewConfigWithRoute<
  TRoute extends AnyAbstractRouteEntity,
> {
  route: TRoute;
  view?: RouteViewComponent<TRoute>;
  /**
   * Case when route is not opened
   */
  fallback?: JSX.Element;
  children?:
    | JSX.Element
    | ((
        params: RouteViewProps<TRoute>['params'],
        route: TRoute,
      ) => JSX.Element);
}

export type RouteViewConfig<TRoute extends AnyAbstractRouteEntity> =
  | RouteViewConfigWithRoute<TRoute>
  | RouteViewConfigWithoutRoute;

export type RouteViewProps<TRoute extends AnyAbstractRouteEntity> = {
  children?: JSX.Element;
  params: TRoute extends AnyRoute
    ? Exclude<TRoute['params'], null | undefined>
    : TRoute extends AnyVirtualRoute
      ? TRoute['params']
      : never;
};

export function RouteView<TRoute extends AnyAbstractRouteEntity>(
  props: RouteViewConfig<TRoute>,
): JSX.Element {
  const group = useRouteViewGroup();

  const isWithRoute = () => 'route' in props;

  const route = () =>
    isWithRoute()
      ? (props as RouteViewConfigWithRoute<TRoute>).route
      : undefined;

  const isOpening = () => {
    const r = route();
    return r && 'isOpening' in r ? Boolean(r.isOpening) : false;
  };

  const isOpenedOrOpening = () => {
    const r = route();
    return r ? r.isOpened || isOpening() : false;
  };

  const params = () => {
    const r = route();
    return r && 'params' in r ? r.params : {};
  };

  // Register with parent RouteViewGroup if present
  if (group) {
    const r = route();
    if (r) {
      group.registerRoute(r);
    }
  }

  // No route prop — render children directly
  if (!isWithRoute()) {
    return typeof props.children === 'function'
      ? (props.children as () => JSX.Element)()
      : (props.children as JSX.Element);
  }

  // Route not opened and not opening — render fallback
  if (!isOpenedOrOpening()) {
    return ((props as RouteViewConfigWithRoute<TRoute>).fallback ??
      null) as JSX.Element;
  }

  const viewComponent = () => (props as RouteViewConfigWithRoute<TRoute>).view;
  const children = () => props.children;

  // View component provided
  if (viewComponent()) {
    return (
      <Dynamic component={viewComponent()!} params={params()}>
        {typeof children() === 'function'
          ? undefined
          : (children() as JSX.Element)}
      </Dynamic>
    );
  }

  // Render function children
  if (typeof children() === 'function') {
    return (children() as (p: any, r: any) => JSX.Element)(params(), route());
  }

  return ((children() as JSX.Element) ?? null) as JSX.Element;
}
